<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/09 16:11:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=greed',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
